on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
        default: "default"

jobs:
  hello:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: echo path
        run: echo "${{ github.action_path }}"
      - name: say hello
        run: bash .github/scripts/say_hello.sh "${{ inputs.username }}"
